---
- name: playbook2
  hosts: servers
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: UNInstall httpd
      yum:
        name: httpd
        state: absent
    
    - name: remove index test page
      file:
        state: absent
        path: /var/www/html/index.html
    
    - name: enable 80
      firewalld:
        zone: public
        port: 80/tcp
        state: disabled
        permanent: true
    
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted