---

- name: Allow full read/write access through SELinux for el7+
  seboolean:
    name: ftpd_full_access
    state: yes
    persistent: yes


- name: Check if ftp_home_dir exists
  shell: getsebool -a | grep '^ftp_home_dir\b'
  register: var_exists
  failed_when: false
  changed_when: false
  tags: vsftpd


- name: Allow access to home directories
  seboolean:
    name: ftp_home_dir
    state: yes
    persistent: yes