---
# handlers file for vsftpd

- name: restart vsftpd
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_service_state != 'stopped'
  ignore_errors: yes

- name: run restorecon
  command: restorecon -v /var/ftp/pub