---
# handlers file for inshttpd

- name: start Apache
  service:
    name: httpd
    enabled: yes
    state: started

- name: restart firewalld
  service:
    name: firewalld
    enabled: yes
    state: restarted

- name: restart Apache
  systemd:
    name: httpd
    state: restarted


