---
# handlers file for inshttpd

- name: restart firewalld
  service:
    name: firewalld
    enabled: yes
    state: restarted

- name: restart apache
  systemd:
    name: httpd
    state: restarted


